#!/usr/bin/env node
// Reads /content/**/*.md and generates src/lib/data.ts.
// Re-run via `npm run build:content` (also triggered by predev/prebuild).

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import matter from 'gray-matter';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '..');
const CONTENT = path.join(ROOT, 'content');
const OUT = path.join(ROOT, 'src/lib/data.ts');

function readMd(file) {
  return matter(fs.readFileSync(file, 'utf8'));
}

function readSingle(rel) {
  return readMd(path.join(CONTENT, rel));
}

function readDir(rel) {
  const dir = path.join(CONTENT, rel);
  if (!fs.existsSync(dir)) return [];
  return fs.readdirSync(dir)
    .filter(f => f.endsWith('.md'))
    .sort()
    .map(f => ({ file: f, ...readMd(path.join(dir, f)) }));
}

function parseSections(body) {
  const out = {};
  const normalized = '\n' + body.trim();
  for (const part of normalized.split(/\n## /).filter(Boolean)) {
    const nl = part.indexOf('\n');
    if (nl < 0) continue;
    const key = part.slice(0, nl).trim().toLowerCase();
    const val = part.slice(nl + 1).trim();
    if (key && val) out[key] = val;
  }
  return out;
}

function parseBullets(body) {
  return body.split('\n')
    .map(l => l.trim())
    .filter(l => l.startsWith('- '))
    .map(l => l.slice(2).trim());
}

const identity = readSingle('identity.md').data;
const kpis        = readSingle('kpis.md').data.items;
const gauges      = readSingle('gauges.md').data.items;
const definitions = readSingle('definitions.md').data.items;
const sections    = readSingle('sections.md').data.items;

const skillGroups = readDir('skill-groups').map(f => f.data);

const projects = readDir('projects').map(f => {
  const body = parseSections(f.content);
  return {
    ...f.data,
    problem: body.problem ?? '',
    solution: body.solution ?? '',
    value: body.value ?? '',
  };
});

const experience = readDir('experience').map(f => ({
  ...f.data,
  missions: parseBullets(f.content),
}));

const education = readDir('education').map(f => f.data);
const certs     = readDir('certs').map(f => f.data);

function emit(name, value) {
  return `export const ${name} = ${JSON.stringify(value, null, 2)};\n`;
}

const out =
`// AUTO-GENERATED by scripts/build-content.mjs — do not edit by hand.
// Source files live under /content/. Run \`npm run build:content\` to regenerate.

${emit('IDENTITY', identity)}
${emit('KPIS', kpis)}
${emit('GAUGES', gauges)}
${emit('PROJECTS', projects)}
${emit('SKILL_GROUPS', skillGroups)}
${emit('EXPERIENCE', experience)}
${emit('EDUCATION', education)}
${emit('CERTS', certs)}
${emit('DEFINITIONS', definitions)}
${emit('SECTIONS', sections)}`;

fs.mkdirSync(path.dirname(OUT), { recursive: true });
fs.writeFileSync(OUT, out);
console.log(`✓ wrote ${path.relative(ROOT, OUT)} (${projects.length} projects, ${experience.length} jobs, ${certs.length} certs, ${education.length} edu)`);
